# Generated by Django 5.1.7 on 2025-03-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pessoas', models.IntegerField(default=100)),
                ('total_mesas', models.IntegerField(default=30)),
            ],
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='data',
            new_name='dia',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(choices=[('almoço', 'Almoço'), ('jantar', 'Jantar')], default='almoço', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_pessoas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidade',
            field=models.IntegerField(default=10),
        ),
    ]
