# Generated by Django 5.1.7 on 2025-03-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_configuracaorestaurante_rename_data_reserva_dia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoRestaurante',
        ),
    ]
