# Generated by Django 5.1.7 on 2025-03-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_delete_configuracaorestaurante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade_pessoas', models.IntegerField(default=20)),
                ('capacidade_mesas', models.IntegerField(default=3)),
            ],
        ),
    ]
